project:
  type: website

website:
  title: "Blog de Hugo Sanchez Nieto"
  favicon: "favicon.jpg"

  navbar:
    logo: "icono.jpg"
    right:
      - text: "Sobre mí"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hugo-sanchez-nieto-marketing/
        aria-label: LinkedIn

  page-footer:
    left: "©2026 Hugo Sánchez Nieto"
    center: "Hecho con Quarto"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/hugo-sanchez-nieto-marketing/
        aria-label: LinkedIn

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
