{
  "hash": "9de1e2bb4c9e2988cf1611050ba1e5eb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inferencia estadística en R: confianza y significación\"\ndescription: \"Contrastes sobre media y varianza (una y dos poblaciones) + normalidad y aleatoriedad.\"\nauthor: \"Hugo Sánchez Nieto\"\ndate: \"2026-01\"\ncategories: [R, Estadística, Inferencia]\nimage: \"thumbnail.png\"\n---\n\n## Objetivo\n\nRealizar inferencia sobre **media y varianza** en **una** y **dos poblaciones**, usando `t.test()` y `var.test()`,\ny cerrar con comprobaciones típicas: **normalidad** y **aleatoriedad**. \n\n---\n\n## Preparación\n\nUsaremos el dataset `cars` (incluido en R). \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(cars)\nspeed <- cars$speed\ndist  <- cars$dist\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(nortest)  # lillie.test\nlibrary(tseries)  # runs.test\nlibrary(car)      # leveneTest\n```\n:::\n\n\n## 1) p-valor y decisión\n\nEl p-valor se usa para decidir si rechazamos H0 al nivel de significación elegido (10%, 5%, 1%).\n\nCreo un helper para imprimir decisiones de forma uniforme:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecision <- function(p, alpha = 0.05, h0 = \"H0\") {\n  if (is.na(p)) return(\"p-value NA\")\n  if (p < alpha) paste(\"Rechazo\", h0, \"(p <\", alpha, \")\")\n  else paste(\"No rechazo\", h0, \"(p ≥\", alpha, \")\")\n}\n```\n:::\n\n\n## 2) Inferencia para una población (media)\n\nEjemplo clásico: contrastar si la media de speed es 17, con contrastes bilateral y unilaterales (greater/less).\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_2colas <- t.test(speed, mu = 17)  # por defecto: two.sided\nt_mayor  <- t.test(speed, mu = 17, alternative = \"greater\")\nt_menor  <- t.test(speed, mu = 17, alternative = \"less\")\n\nt_2colas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  speed\nt = -2.1397, df = 49, p-value = 0.03739\nalternative hypothesis: true mean is not equal to 17\n95 percent confidence interval:\n 13.89727 16.90273\nsample estimates:\nmean of x \n     15.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(t_2colas$p.value, h0 = \"media = 17\"), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo media = 17 (p < 0.05 ) \n```\n\n\n:::\n\n```{.r .cell-code}\nt_mayor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  speed\nt = -2.1397, df = 49, p-value = 0.9813\nalternative hypothesis: true mean is greater than 17\n95 percent confidence interval:\n 14.1463     Inf\nsample estimates:\nmean of x \n     15.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(t_mayor$p.value, h0 = \"media = 17 (alt: mayor)\"), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo rechazo media = 17 (alt: mayor) (p ≥ 0.05 ) \n```\n\n\n:::\n\n```{.r .cell-code}\nt_menor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  speed\nt = -2.1397, df = 49, p-value = 0.01869\nalternative hypothesis: true mean is less than 17\n95 percent confidence interval:\n    -Inf 16.6537\nsample estimates:\nmean of x \n     15.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(t_menor$p.value, h0 = \"media = 17 (alt: menor)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo media = 17 (alt: menor) (p < 0.05 ) \n```\n\n\n:::\n:::\n\n\n\nRegión de rechazo\n\nEn el temario también compara el valor experimental con el teórico (qt)\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = length(speed) - 1)  # dos colas al 5%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.009575\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(0.95,  df = length(speed) - 1)  # una cola (greater) al 5%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.676551\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(0.05,  df = length(speed) - 1)  # una cola (less) al 5%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.676551\n```\n\n\n:::\n:::\n\n\n\n## 3) Inferencia para dos poblaciones (varianzas y medias)\n\n### 3.1 Igualdad de varianzas (F-test)\n\nComparamos speed y dist con var.test(), tanto bilateral como unilateral (por ejemplo, ratio < 1)\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(speed); var(dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27.95918\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 664.0608\n```\n\n\n:::\n\n```{.r .cell-code}\nf_2colas <- var.test(speed, dist)\nf_menor  <- var.test(speed, dist, alternative = \"less\")\n\nf_2colas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  speed and dist\nF = 0.042103, num df = 49, denom df = 49, p-value < 2.2e-16\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.02389265 0.07419404\nsample estimates:\nratio of variances \n        0.04210335 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(f_2colas$p.value, h0 = \"varianzas iguales (two.sided)\"), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo varianzas iguales (two.sided) (p < 0.05 ) \n```\n\n\n:::\n\n```{.r .cell-code}\nf_menor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  speed and dist\nF = 0.042103, num df = 49, denom df = 49, p-value < 2.2e-16\nalternative hypothesis: true ratio of variances is less than 1\n95 percent confidence interval:\n 0.00000000 0.06767227\nsample estimates:\nratio of variances \n        0.04210335 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(f_menor$p.value, h0 = \"ratio de varianzas = 1 (alt: < 1)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo ratio de varianzas = 1 (alt: < 1) (p < 0.05 ) \n```\n\n\n:::\n:::\n\n\nRegión crítica\n\n::: {.cell}\n\n```{.r .cell-code}\nqf(0.025, df1 = length(speed)-1, df2 = length(dist)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5674762\n```\n\n\n:::\n\n```{.r .cell-code}\nqf(0.975, df1 = length(speed)-1, df2 = length(dist)-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.762189\n```\n\n\n:::\n:::\n\n\n### 3.2 Igualdad de medias (t-test para dos muestras)\n\nSi no asumimos varianzas iguales, usamos Welch (var.equal = FALSE, que es el valor por defecto)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2_2colas <- t.test(speed, dist, var.equal = FALSE)\nt2_2colas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  speed and dist\nt = -7.4134, df = 53.119, p-value = 9.628e-10\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -35.04152 -20.11848\nsample estimates:\nmean of x mean of y \n    15.40     42.98 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(t2_2colas$p.value, h0 = \"medias iguales (Welch)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo medias iguales (Welch) (p < 0.05 ) \n```\n\n\n:::\n:::\n\n\nUnilateral (por ejemplo, media de speed menor que dist):\n\n::: {.cell}\n\n```{.r .cell-code}\nt2_menor <- t.test(speed, dist, var.equal = FALSE, alternative = \"less\")\nt2_menor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  speed and dist\nt = -7.4134, df = 53.119, p-value = 4.814e-10\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -21.35209\nsample estimates:\nmean of x mean of y \n    15.40     42.98 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(t2_menor$p.value, h0 = \"medias iguales (alt: speed < dist)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo medias iguales (alt: speed < dist) (p < 0.05 ) \n```\n\n\n:::\n:::\n\n\nRegión crítica\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = t2_2colas$parameter)  # df de Welch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.005641\n```\n\n\n:::\n:::\n\n\n\n## 4) Inferencia con más de dos grupos (ANOVA) + homogeneidad de varianzas\n\nEl temario construye un factor con 3 niveles (0,1,2) y hace:\n\n- resúmenes por grupo (tapply)\n\n- ANOVA (aov)\n\n- Levene (homogeneidad de varianzas)\n\n- TukeyHSD (comparaciones por pares)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2022)\nterna <- rbinom(length(speed), 2, 0.5)\nfactores_terna <- factor(terna)\n\ntable(factores_terna)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfactores_terna\n 0  1  2 \n13 23 14 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(speed, factores_terna, summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$`0`\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   7.00   10.00   12.00   13.38   15.00   24.00 \n\n$`1`\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    4.0    12.5    17.0    15.7    19.5    24.0 \n\n$`2`\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   4.00   14.00   16.50   16.79   20.00   25.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ntapply(speed, factores_terna, var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       0        1        2 \n22.75641 27.31225 31.87363 \n```\n\n\n:::\n\n```{.r .cell-code}\nanova_speed <- aov(speed ~ factores_terna)\n\nleveneTest(speed ~ factores_terna, center = mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n      Df F value Pr(>F)\ngroup  2  0.1895  0.828\n      47               \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(anova_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value Pr(>F)\nfactores_terna  2   81.7   40.85    1.49  0.236\nResiduals      47 1288.3   27.41               \n```\n\n\n:::\n\n```{.r .cell-code}\nTukeyHSD(anova_speed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = speed ~ factores_terna)\n\n$factores_terna\n        diff       lwr      upr     p adj\n1-0 2.311037 -2.085524 6.707597 0.4177758\n2-0 3.401099 -1.479168 8.281366 0.2209356\n2-1 1.090062 -3.205008 5.385133 0.8130943\n```\n\n\n:::\n:::\n\n\nNo rechazo homogeneidad de varianzas (Levene, p=0.828).\nNo rechazo igualdad de medias (ANOVA, p=0.236).\n\n## 5) Hipótesis de partida: normalidad y aleatoriedad\n\n### 5.1 Normalidad\n\nEn el temario se aplican KS, Shapiro y Lilliefors, y se recuerda que si p-valor > 0.05 no se rechaza normalidad.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nks <- ks.test(speed, pnorm, mean(speed), sd(speed))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in ks.test.default(speed, pnorm, mean(speed), sd(speed)): ties should\nnot be present for the one-sample Kolmogorov-Smirnov test\n```\n\n\n:::\n\n```{.r .cell-code}\nsw <- shapiro.test(speed)\nlf <- lillie.test(speed)\n\nks; cat(decision(ks$p.value, h0=\"normalidad (KS)\"), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAsymptotic one-sample Kolmogorov-Smirnov test\n\ndata:  speed\nD = 0.068539, p-value = 0.9729\nalternative hypothesis: two-sided\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo rechazo normalidad (KS) (p ≥ 0.05 ) \n```\n\n\n:::\n\n```{.r .cell-code}\nsw; cat(decision(sw$p.value, h0=\"normalidad (Shapiro)\"), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  speed\nW = 0.97765, p-value = 0.4576\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo rechazo normalidad (Shapiro) (p ≥ 0.05 ) \n```\n\n\n:::\n\n```{.r .cell-code}\nlf; cat(decision(lf$p.value, h0=\"normalidad (Lilliefors)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  speed\nD = 0.068539, p-value = 0.8068\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo rechazo normalidad (Lilliefors) (p ≥ 0.05 ) \n```\n\n\n:::\n:::\n\n\n### 5.2 Aleatoriedad (test de rachas)\n\nSe contrasta H0: “hay aleatoriedad” usando runs.test() sobre la variable binaria speed > median(speed)\n\n::: {.cell}\n\n```{.r .cell-code}\nruns <- runs.test(as.factor(speed > median(speed)))\nruns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRuns Test\n\ndata:  as.factor(speed > median(speed))\nStandard Normal = -6.8583, p-value = 6.966e-12\nalternative hypothesis: two.sided\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(decision(runs$p.value, h0=\"aleatoriedad (Runs test)\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRechazo aleatoriedad (Runs test) (p < 0.05 ) \n```\n\n\n:::\n:::\n\n\nEl runs test depende del orden de la serie; con datos ordenados o con estructura temporal suele rechazar aleatoriedad.\n\n## Conclusiones\n\n- t.test() y var.test() permiten inferencia sobre media/varianza con hipótesis bilateral o unilateral mediante alternative.\n\n- El p-valor guía la decisión al nivel de significación elegido.\n\n- Para ANOVA: comprobar homogeneidad (Levene) y, si procede, comparaciones múltiples (Tukey).\n\n- Para justificar inferencia clásica: comprobar supuestos como normalidad y aleatoriedad.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}